### PR TITLE
Fixing missing configuration, the configuration screen will work again.

### PR DESCRIPTION
**Pull request by ranzou06**
with this fix the config screen will be working again.

### CODE REVIEW

**Comment by ranzou06** [comment]
any chance on merging that changes on the master branch?

**Comment by phixom** [comment]
I would like to use this pull request, please merge it.

**Comment by ranzou06** [comment]
you can find the updated version [here](https://plugins.jetbrains.com/plugin/10163-javadoc2)

**Comment by wyaoo** [comment]
> you can find the updated version [here](https://plugins.jetbrains.com/plugin/10163-javadoc2)

thanks a lot! It really works

**Pull request closed without merging**
